name: Bump Homebrew Formula

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  bump-formula-pr:
    name: Bump Homebrew formula
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@75ed025ff3ad1d617862838b342b06d613a0ddf3 # 3.10.1
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}
          formula: rbspy
          tag: ${{ github.ref }}
          revision: ${{ github.sha }}
