name: Release to crates.io

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  rust-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: publish ruby-structs crate
        continue-on-error: true
        run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
          cd ruby-structs
          cargo publish
      - name: publish rbspy crate
        run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
          cargo publish
